### ISSUE TITLE
Proposal status

### ISSUE THREAD

**Issue by macor161** [samuelgoto/proposal-block-params#35]
Hello, not really an issue but I would like to know what is the current status of this proposal, as it hasn’t been updated for over a year now.

**Comment by littledan** [comment]
When block parameters were presented, they faced significant doubts due to the overlap with arrow functions and implementation concerns for break/return/continue semantics. See some context in https://github.com/tc39/proposals/issues/212#issuecomment-488367386 . For these reasons, I believe it is unlikely to move forward in TC39's process in its current form.

**Comment by macor161** [comment]
@littledan thanks for the clarification. Closing this.
